### PR TITLE
remove enhance.com from block lists, as it is a hosting software company

### PR DESCRIPTION
**Pull request by mygnu**
Hi I'm your vpn customer, also work for Enhance Hosting Ltd. This PR removes all references to enhance.com which is a software company and should not be blocked by default. This can confirm by visiting the website, or can contact me at harry@enhance.com or owner of the company at adam@enhance.com for any further questions.

### CODE REVIEW

**Comment by jbjorkang** [comment]
Thanks for this. Do you know if this URL is removed upstream from any of the lists we pull in?

**Comment by mygnu** [comment]
I'm aware that AdGuard has removed us from their list

**Comment by jbjorkang** [comment]
> I'm aware that AdGuard has removed us from their list

Okay. I shall rebuild the lists soon. Hopefully it is as simple as that.

**Comment by jbjorkang** [comment]
```
$ grep -R enhance.com lists/relay/
lists/relay/privacy/easylist-privacy:enhance.com
lists/relay/adblock/AdguardDNS:poisonoustrolleyenhance.com
lists/relay/adblock/AdguardDNS:enhance.com
lists/relay/adblock/easylist-adblock:poisonoustrolleyenhance.com
```

These appear to have your URL still. Perhaps it is best to contact them and ask them to remove the URL.

**Pull request closed without merging**
